apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: johnny
  namespace: nais
spec:
  ingresses:
    - https://johnny.prod-gcp.nav.cloud.nais.io
  image: {{ image }}
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
