name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build and push image and SBOM to OCI registry
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: nais 
        identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    - name: Deploy to dev
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp 
        RESOURCE: .nais/app.yaml
        VAR: image=${{ steps.docker-build-push.outputs.image }}
    - name: Deploy to prod
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp 
        RESOURCE: .nais/app.yaml
        VAR: image=${{ steps.docker-build-push.outputs.image }}
