on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    permissions:
      contents: "read"
      id-token: "write"
    name: hack
    runs-on: ubuntu-latest
    steps:
      - name: Run johnny-action
        uses: navikt/johnny-action@main

