on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          echo "Hello World"

